//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc5Cv.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblEgitimlerim
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Bu alanýn doldurulmasý zorunludur.")]
        public string Baslik { get; set; }
        public string AltBaslik1 { get; set; }
        public string AltBaslik2 { get; set; }
        public string Gno { get; set; }
        
        [StringLength(50,ErrorMessage ="Maximum uzunluk 50 karakter olacak þekilde giriniz.")]
        public string Tarih { get; set; }
    }
}
