//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc5Cv.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSertifikalarim
    {
        public int Id { get; set; }
        public string Aciklama { get; set; }
        public string Tarih { get; set; }
    }
}
